package com.issi.enums;

public enum ConfigProperties  {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOT,
    FAILEDSTEPSCREENSHOT,
    SKIPPEDSTEPSCREENSHOT,
    BROWSER,
    RETRYFAILEDTESTS
}
